export const keys = {
    text: [
        [
            { key: '1', key_u: '1', long: '' },
            { key: '2', key_u: '2', long: '' },
            { key: '3', key_u: '3', long: '' },
            { key: '4', key_u: '4', long: '' },
            { key: '5', key_u: '5', long: '' },
            { key: '6', key_u: '6', long: '' },
            { key: '7', key_u: '7', long: '' },
            { key: '8', key_u: '8', long: '' },
            { key: '9', key_u: '9', long: '' },
            { key: '0', key_u: '0', long: '' },
            { key: '=', key_u: '=', long: '' },
            { key: 'backspace', key_u: 'backspace', long: '' },
        ],
        [
            { key: 'q', key_u: 'Q', long: '' },
            { key: 'w', key_u: 'W', long: '' },
            { key: 'e', key_u: 'E', long: '' },
            { key: 'r', key_u: 'R', long: '' },
            { key: 't', key_u: 'T', long: '' },
            { key: 'y', key_u: 'Y', long: '' },
            { key: 'u', key_u: 'U', long: '' },
            { key: 'i', key_u: 'I', long: '' },
            { key: 'o', key_u: 'O', long: '' },
            { key: 'p', key_u: 'P', long: '' },
            { key: '-', key_u: '-', long: '' },
            { key: '_', key_u: '_', long: '' },
            { key: '+', key_u: '+', long: '' },
        ],
        [
            { key: 'a', key_u: 'A', long: '' },
            { key: 's', key_u: 'S', long: '' },
            { key: 'd', key_u: 'D', long: '' },
            { key: 'f', key_u: 'F', long: '' },
            { key: 'g', key_u: 'G', long: '' },
            { key: 'h', key_u: 'H', long: '' },
            { key: 'j', key_u: 'J', long: '' },
            { key: 'k', key_u: 'K', long: '' },
            { key: 'l', key_u: 'L', long: '' },
            { key: ';', key_u: ';', long: '' },
            { key: ':', key_u: ':', long: '' },
            { key: 'enter', key_u: 'enter', long: '' },
        ],
        [
            { key: 'shift', key_u: 'shift', long: '' },
            { key: 'z', key_u: 'Z', long: '' },
            { key: 'x', key_u: 'X', long: '' },
            { key: 'c', key_u: 'C', long: '' },
            { key: 'v', key_u: 'V', long: '' },
            { key: 'b', key_u: 'B', long: '' },
            { key: 'n', key_u: 'N', long: '' },
            { key: 'm', key_u: 'M', long: '' },
            { key: '.', key_u: '.', long: '' },
            { key: '@', key_u: '@', long: '' },
            { key: 'space', key_u: 'space', long: '' },
        ]
    ],

    number: [
        [
            { key: '1' },
            { key: '2' },
            { key: '3' },
            { key: '4' },
            { key: '5' },
            { key: '6' },
            { key: '7' },
            { key: '8' },
            { key: '9' },
            { key: '0' },
            { key: 'enter' },
            { key: 'backspace' },
        ]
    ]
} 
